-- Baseline schema bootstrap from types/supabase.ts
-- Creates all typed public tables if they do not exist.
-- Safe to run repeatedly.

begin;

create extension if not exists pgcrypto;

create table if not exists public.guest (
  id uuid primary key default gen_random_uuid(),
  full_name text null,
  email text null,
  contact_number text null,
  gender text null,
  nationality text null,
  address text null,
  valid_id jsonb null,
  created_at timestamptz not null default now()
);

create table if not exists public.room_types (
  id uuid primary key default gen_random_uuid(),
  name text null,
  description text null,
  image text null,
  room_size text null,
  max_guest integer null,
  price numeric(12,2) null,
  peak_season_price numeric(12,2) null,
  created_at timestamptz not null default now()
);

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  room_id text not null,
  room_number integer not null,
  room_type_id uuid null references public.room_types(id),
  status text not null,
  area text null,
  description text null,
  remarks text null,
  bookings jsonb[] null,
  created_at timestamptz not null default now()
);

create table if not exists public."function-rooms" (
  id uuid primary key default gen_random_uuid(),
  room_number integer null,
  type text null,
  max_guest integer null,
  size text null,
  description text null,
  image text null,
  status text null,
  remarks text null,
  function_hall_bookings jsonb[] null,
  created_at timestamptz not null default now()
);

create table if not exists public.booking_count (
  id bigint generated by default as identity primary key,
  type text null,
  count integer null,
  created_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  booking_number text null,
  guest_id uuid null references public.guest(id),
  room_id uuid null references public.rooms(id),
  room_type_id uuid null references public.room_types(id),
  checked_in timestamptz null,
  checked_out timestamptz null,
  number_of_guests numeric(10,2) null,
  company text null,
  places_last_visited text null,
  purpose text null,
  special_requests jsonb[] null,
  recent_sickness text null,
  payment_status text null,
  payment_method text null,
  booking_source text null,
  amount_paid numeric(12,2) null,
  total_add_ons numeric(12,2) null,
  total numeric(12,2) null,
  status text not null default 'pending',
  created_at timestamptz null default now()
);

create table if not exists public.function_hall_bookings (
  id uuid primary key default gen_random_uuid(),
  booking_number text null,
  guest_id uuid null references public.guest(id),
  room_id uuid null references public."function-rooms"(id),
  event_type text null,
  event_start timestamptz null,
  event_end timestamptz null,
  number_of_guest integer null,
  notes text null,
  occupancy_type text null,
  status text null default 'pending',
  booking_source text null,
  payment_status text null,
  payment_method text null,
  amount_paid numeric(12,2) null,
  total_amount numeric(12,2) null,
  balance numeric(12,2) null,
  created_at timestamptz not null default now()
);

create table if not exists public.feedback (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  email text not null,
  room_number text not null,
  check_in date not null,
  check_out date not null,
  rating integer not null,
  recommend text not null,
  comments text null,
  created_at timestamptz not null default now()
);

create table if not exists public.inventory (
  id uuid primary key default gen_random_uuid(),
  name text null,
  description text null,
  quantity integer null,
  price numeric(12,2) null,
  status text null,
  created_at timestamptz not null default now()
);

create table if not exists public.room_type_add_ons (
  id uuid primary key default gen_random_uuid(),
  room_type_id uuid not null references public.room_types(id) on delete cascade,
  inventory_id uuid not null references public.inventory(id),
  quantity_limit integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text null,
  message text null,
  type text null,
  is_read boolean null default false,
  created_at timestamptz not null default now()
);

create table if not exists public."room-reports" (
  id uuid primary key default gen_random_uuid(),
  report_type text null,
  room_number text null,
  guest_name text null,
  item_category text null,
  item_name text null,
  damage_type text null,
  quantity integer null,
  estimated_cost numeric(12,2) null,
  notes text null,
  status text null,
  reported_by text null,
  report_date date null,
  resolved_date date null,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_rooms_room_id_unique on public.rooms(room_id);
create unique index if not exists idx_rooms_room_number_unique on public.rooms(room_number);
create unique index if not exists idx_function_rooms_room_number_unique on public.function_rooms(room_number);
create index if not exists idx_bookings_guest_id on public.bookings(guest_id);
create index if not exists idx_bookings_room_id on public.bookings(room_id);
create index if not exists idx_bookings_room_type_id on public.bookings(room_type_id);
create index if not exists idx_room_type_add_ons_room_type_id on public.room_type_add_ons(room_type_id);
create index if not exists idx_room_type_add_ons_inventory_id on public.room_type_add_ons(inventory_id);
create index if not exists idx_function_hall_bookings_guest_id on public.function_hall_bookings(guest_id);
create index if not exists idx_function_hall_bookings_room_id on public.function_hall_bookings(room_id);

commit;
